# Generated by Django 6.0.2 on 2026-05-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис активу'),
        ),
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets_images/', verbose_name='Логотип'),
        ),
    ]
