# Generated by Django 6.0.2 on 2026-05-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_newsletter_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрено'),
        ),
    ]
