# Generated by Django 6.0.2 on 2026-05-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_review_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='api_ticker',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тікер для API'),
        ),
    ]
