# Generated by Django 6.0.2 on 2026-05-08 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_asset_api_ticker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва тарифу (напр. VIP)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ціна $')),
                ('description', models.TextField(verbose_name='Що входить у підписку')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.subscriptionplan', verbose_name='Тарифний план')),
            ],
        ),
    ]
